version: '3.8'

services:
  db:
    image: postgres:12.16
    container_name: db_infoBot
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_DB: infoBot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: 
      - ./DB_infoBot/infoBot:/var/lib/postgresql/data
    restart: always
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3