version: '3.8'

services:

  db:
    image: postgres:16-bullseye
    container_name: db_javaBot
    environment:
      POSTGRES_DB: infoBot
      POSTGRES_USER: postgres_1
      POSTGRES_PASSWORD: ${DB_postgres}
    volumes:
      - ./DB_infoBot/infoBot:/var/lib/postgresql/data
    networks:
      - boto_net
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_1 -d infoBot"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    image: 009123/tlg_bot:3.0
    container_name: javabot
    environment:
      HOST: db_javaBot
      PORT: 5432
      DB: infoBot
      DB_HOST: db
      ENCRYPTION_PASSWORD: ${ENCRYPTION_PASSWORD}
    networks:
      - boto_net
    restart: always
    depends_on:
       db:
         condition: service_healthy

networks:
  boto_net:
    name: boto_net
