jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${ENCRYPTION_PASSWORD}
    iv-generator-classname: org.jasypt.iv.NoIvGenerator



bot.name: newInfoJava_bot
bot.token: ENC(OepDFUKw/B/0x6qziWcrIIDQuoDyjXjHgfJbzyFKckkiU465R0IWIZP5WW83ZRNpsjAyhYxfTHw=)
bot.ownerID: 994138843


spring:
  datasource:
    #url: jdbc:postgresql://db:5432/infoBot
    #url: jdbc:postgresql://127.0.0.1:5432/infoBot
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:5432/infoBot
    username: postgres
    password: ENC(meZs5HRHLgkbTC6tnK5Yur/vzTwczaNM)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


