jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${ENCRYPTION_PASSWORD}
    iv-generator-classname: org.jasypt.iv.NoIvGenerator



bot.name: newInfoJava_bot
bot.token: ENC(YRtNKQERH8ViRyCbqCBhWo6DDmKQtiqazLKMDT0f6YMsYWmhmiNMscb03fYY3Y67Jr6fG1waEtI=)
bot.ownerID: 994138843


spring:
  datasource:
    #url: jdbc:postgresql://db:5432/infoBot
    #url: jdbc:postgresql://127.0.0.1:5432/infoBot
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:5432/infoBot
    username: postgres
    password: ENC(GSTv7LWJ0tOhw+chfitIkKnSUSsIFrnL)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


