version: '3.8'

services:

  db:
    image: postgres:12.16
    container_name: db_javaBot
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_DB: infoBot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes: 
      - ./DB_infoBot/infoBot:/var/lib/postgresql/data
    networks: 
      - boto_net
    restart: always

    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend:
    image: 009123/tlg_bot:0.0.2
    container_name: javabot
    environment:
      HOST: db_javaBot
      PORT: 5432
      DB: infoBot
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      cryptosword: yustasdev
      DB_HOST: db
    networks: 
      - boto_net
    restart: always
    depends_on:
       db:
         condition: service_healthy

networks: 
  boto_net:
    name: boto_net


    